name: CodeCov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      OS: ubuntu-latest
      PYTHON: '3.12'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest Shelegia_Motta_2021_Test/*Test.py
        coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
